name: 'Deploy to AWS S3'
description: 'Deploy to AWS S3'
inputs:
  bucket:
    description: 'S3 Bucket name'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'ap-northeast-2'
  dist-folder:
    description: 'The folder containing the website files'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website'  
runs:
  using: 'docker'
  image: 'Dockerfile'